#!/bin/sh

BRANCH=${1:-autosave}

echo "  About to watch"
echo "    please have inotifywait and git..."
echo ""

checkout () {
  git checkout -b ${1} 2> /dev/null
  git checkout ${1}
}

commit () {
  git add .
  git commit --no-gpg-sign -m "${1:-auto-commit}"
  git push origin ${2:-$BRANCH}
}

commit_and_reset_comment() {
  commit $COMMENT
  COMMENT=""
}

branch () {
  checkout ${1}
}

delete () {
  git branch -d ${1}
}

merge () {
  checkout master
  git merge --no-gpg-sign $BRANCH
  git push origin master
  checkout $BRANCH
}

rebase () {
  git rebase --no-gpg-sign ${1:-master}
}


checkout $BRANCH
commit_and_reset_comment


#inotifywait -m ./ -e CLOSE_WRITE -e CREATE |
(inotifywait -m ./ -e CLOSE_WRITE -e CREATE & cat) |
  while read path action file; do
    echo "$path" "$action" "$file"

    case $path in
      "~")
          echo "home branch: ${1}"
          checkout "$BRANCH"
            ;;

      "b")
          echo "branch"
          branch "$action"
            ;;

      "c")
          echo "comment"
          COMMENT="$action"
            ;;

      "d")
          echo "delete"
          delete
            ;;

      "m")

          echo "MMM merging"
          merge
            ;;

      "r")
          echo "rebase"
          rebase
            ;;

      *)
          echo "CCC committing $SUSPEND"
          commit_and_reset_comment
            ;;
    esac

  done
