#!/bin/bash

PORT=${1:-4444}
UPDATES_PORT=${3:-4445}
FILE=${2:-index.html}
HTTP="HTTP/1.1"
STATUS="200"
HEADER="Server: custom\r\n"

rm .updates 2> /dev/null; mkfifo .updates

while :
do
  nc -l $PORT < <(cat <(echo -e "$HTTP $STATUS\r\n$HEADER\r\n") $FILE) &
  nc -l $UPDATES_PORT < .updates
done