#!/bin/bash

PORT=${1:-4444}
UPDATES_PORT=${2:-4445}
FILE=${3:-index.html}
HTTP="HTTP/1.1"
STATUS="200"
HEADER="Server: custom\r\n"
HTTP_OK="$HTTP $STATUS\r\n$HEADER\r\n"

rm .updates 2> /dev/null; mkfifo .updates

http_host() {
  nc -l $1 < <(cat <(echo -e "$HTTP_OK") $2)
}

(
  while :
  do
    http_host $PORT $FILE
  done
) &

echo "test"

(
  while :
  do
    http_host $UPDATES_PORT .updates
  done
)