#!/bin/bash

PORT=${1:-4444}
UPDATES_PORT=${2:-4445}
FILE=${3:-index.html}
HTTP="HTTP/1.1"
STATUS="200"
HEADER="Server: custom\r\n"
KA="Connection: keep-alive\r\n"
HTTP_OK="$HTTP $STATUS\r\n$HEADER\r\n"
WS_HEADER="Connection: Upgrade\r\nUpgrade: websocket\r\n"
WS_UPGRADE="$HTTP 101 Switching Protocols\r\n$WS_HEADER\r\n"

rm .updates 2> /dev/null; mkfifo .updates

host_file () {
  while :
  do
    serve_file $1 $2
  done
}


# host_ws () {
#   while :
#   do
#     #serve_ws $1 $2
#   done
# }


host_ws () {
  while :
  do
    nc -l -k $1 < <(cat <(echo -e "$HTTP $STATUS\r\n$KA\r\n") $2)
  done
}

serve_file() {
 nc -l $1 < <(cat <(echo -e "$HTTP_OK") $2)
}

serve_ws() {
  nc -l $1 < <(cat <(echo -e "$WS_UPGRADE") $2)
}

watch () {
  (inotifywait -m ./ -e CLOSE_WRITE -e CREATE & cat < /dev/null) |
    while read path action file; do
      kill $HOST_FILE_PID
      kill $HOST_WS_PID

      (host_file $PORT $FILE) &
      HOST_FILE_PID=$! &
      (host_ws $UPDATES_PORT .updates) &
      HOST_WS_PID=$!
    done
}

(host_file $PORT $FILE) &
HOST_FILE_PID=$! &
(host_ws $UPDATES_PORT .updates) &
HOST_WS_PID=$! &
watch