#!/bin/sh

BRANCH=${1:-autosave}

echo "  About to watch"
echo "    please have inotifywait and git..."
echo ""

checkout () {
  git checkout -b ${1} 2> /dev/null
  git checkout ${1}
}

commit () {
  git add .
  git commit --no-gpg-sign -m "${1:-auto-commit}"
  git push origin ${1:-$BRANCH}
}

commit_and_reset_comment() {
  commit $COMMENT
  $COMMENT=''
}

merge () {
  checkout master
  git merge --no-gpg-sign $BRANCH
  git push origin master
  checkout $BRANCH
}


checkout $BRANCH
commit_and_reset_comment


#inotifywait -m ./ -e CLOSE_WRITE -e CREATE |
(inotifywait -m ./ -e CLOSE_WRITE -e CREATE & cat) |
  while read path action file; do
    echo "$path" "$action" "$file"

    case $path in
      "c")
          echo "comment"
          COMMENT="$action"
            ;;

      "m")

          echo "MMM merging"
          merge
            ;;

      *)
          echo "CCC committing $SUSPEND"
          commit_and_reset_comment
            ;;
    esac

  done
